export interface MenuItem {
  id: string
  nameEn: string
  nameAr: string
  nameRu: string
  nameTr: string
  price: number
  category: string
  description?: {
    en: string
    ar: string
    ru: string
    tr: string
  }
  image?: string
}

export const menuItems: MenuItem[] = [
  // Main Meals
  {
    id: "1",
    nameEn: "Rice with Chicken & Vegetables",
    nameAr: "وجبة رز ودجاج وخضار",
    nameRu: "Рис с курицей и овощами",
    nameTr: "Pirinç, Tavuk ve Sebze",
    price: 225,
    category: "meals",
  },
  {
    id: "2",
    nameEn: "Stuffed Vegetables with Gollash & Grilled Chicken",
    nameAr: "وجبة محاشي وجلاش وفراخ مشوية",
    nameRu: "Фаршированные овощи с голлашем и курицей гриль",
    nameTr: "Karışık Dolma, Gollash ve Izgara Tavuk",
    price: 300,
    category: "meals",
  },
  {
    id: "3",
    nameEn: "Kabsa Half Chicken with Sauce",
    nameAr: "وجبة كبسة نص فرخة مع صوص",
    nameRu: "Кабса с половиной курицы и соусом",
    nameTr: "Kabsa Yarım Tavuk Soslu",
    price: 350,
    category: "meals",
  },
  {
    id: "4",
    nameEn: "Stuffed Pigeon with Soup",
    nameAr: "وجبة حمام محشي مع شوربة",
    nameRu: "Фаршированный голубь с супом",
    nameTr: "İçli Güvercin Çorba ile",
    price: 450,
    category: "meals",
  },
  {
    id: "5",
    nameEn: "Mombar with Panee",
    nameAr: "وجبة ممبار مع بانيه",
    nameRu: "Момбар с пане",
    nameTr: "Mumbar Pane ile",
    price: 300,
    category: "meals",
  },
  {
    id: "6",
    nameEn: "Grilled Whole Chicken",
    nameAr: "فرخة متبلة مشوية",
    nameRu: "Целая курица гриль",
    nameTr: "Tam Izgara Tavuk",
    price: 500,
    category: "meals",
  },
  {
    id: "7",
    nameEn: "Grilled Chicken with Rice (4 persons) + 2 Vegetables",
    nameAr: "فرخة مشوية مع رز 4 أفراد وعلبتين خضار",
    nameRu: "Курица гриль с рисом (4 персоны) + 2 овощных гарнира",
    nameTr: "Izgara Tavuk Pilav ile (4 kişilik) + 2 Sebze",
    price: 900,
    category: "meals",
  },
  {
    id: "8",
    nameEn: "Half Duck with Rice & Molokhia",
    nameAr: "نص بطاية مع رز وملوخية",
    nameRu: "Половина утки с рисом и мулухией",
    nameTr: "Yarım Ördek Pilav ve Mulukhia ile",
    price: 800,
    category: "meals",
  },
  {
    id: "9",
    nameEn: "Whole Roasted Duck",
    nameAr: "بطاية كاملة محمرة",
    nameRu: "Целая жареная утка",
    nameTr: "Tam Kızarmış Ördek",
    price: 1300,
    category: "meals",
  },
  {
    id: "10",
    nameEn: "Hawawshi Bread with Tahini Salad",
    nameAr: "رغيف حواوشي لحمة مع سلطة طحينة",
    nameRu: "Хававши с салатом тахини",
    nameTr: "Hawawshi Ekmek Tahin Salata ile",
    price: 200,
    category: "meals",
  },
  {
    id: "11",
    nameEn: "Grilled Kofta Hati with Bread & Tahini",
    nameAr: "طلب كفتة حاتي مشوية مع عيش وطحينة",
    nameRu: "Кофта хати гриль с хлебом и тахини",
    nameTr: "Izgara Köfte Hati Ekmek ve Tahin ile",
    price: 400,
    category: "meals",
  },
  {
    id: "12",
    nameEn: "Meat with Rice & Vegetables",
    nameAr: "وجبة لحمة مع رز وخضار",
    nameRu: "Мясо с рисом и овощами",
    nameTr: "Et, Pilav ve Sebze",
    price: 400,
    category: "meals",
  },
  {
    id: "13",
    nameEn: "Mombar with Kawari Soup",
    nameAr: "وجبة ممبار مع شوربة كوارع",
    nameRu: "Момбар с супом каваръ",
    nameTr: "Mumbar Paça Çorbası ile",
    price: 475,
    category: "meals",
  },
  {
    id: "14",
    nameEn: "Mix Meal (Yellow Rice, 2 Kofta Hati, 2 Chicken Kofta, Gollash & Bechamel)",
    nameAr: "وجبة ميكس رز أصفر و٢ كفتة حاتي و٢ كفتة دجاج وقطعة جلاش وصينية بشاميل",
    nameRu: "Микс (желтый рис, 2 кофта хати, 2 куриные кофта, голлаш и бешамель)",
    nameTr: "Mix Öğün (Sarı Pilav, 2 Köfte Hati, 2 Tavuk Köfte, Gollash ve Beşamel)",
    price: 550,
    category: "meals",
  },
  {
    id: "15",
    nameEn: "Mix Stuffed Vegetables with Gollash & Panee or Chicken",
    nameAr: "وجبة ميكس محاشي وجلاش وبانيه أو دجاج",
    nameRu: "Микс фаршированные овощи с голлашем и пане или курицей",
    nameTr: "Mix Dolma, Gollash ve Pane veya Tavuk",
    price: 375,
    category: "meals",
  },
  // Dishes
  {
    id: "16",
    nameEn: "Stuffed Vegetables (Medium)",
    nameAr: "طبق محاشي وسط",
    nameRu: "Фаршированные овощи (средний)",
    nameTr: "Karışık Dolma (Orta)",
    price: 275,
    category: "dishes",
  },
  {
    id: "17",
    nameEn: "Stuffed Vegetables (Large)",
    nameAr: "طبق محاشي كبير",
    nameRu: "Фаршированные овощи (большой)",
    nameTr: "Karışık Dolma (Büyük)",
    price: 550,
    category: "dishes",
  },
  {
    id: "18",
    nameEn: "Mombar (Medium)",
    nameAr: "طبق ممبار وسط",
    nameRu: "Момбар (средний)",
    nameTr: "Mumbar (Orta)",
    price: 300,
    category: "dishes",
  },
  {
    id: "19",
    nameEn: "Mombar (Large)",
    nameAr: "طبق ممبار كبير",
    nameRu: "Момбар (большой)",
    nameTr: "Mumbar (Büyük)",
    price: 600,
    category: "dishes",
  },
  {
    id: "20",
    nameEn: "Scalop Panee (Medium)",
    nameAr: "طبق اسكالوب بانيه وسط",
    nameRu: "Эскалоп пане (средний)",
    nameTr: "Pane Şnitzel (Orta)",
    price: 300,
    category: "dishes",
  },
  {
    id: "21",
    nameEn: "Scalop Panee (Large)",
    nameAr: "طبق اسكالوب بانيه كبير",
    nameRu: "Эскалоп пане (большой)",
    nameTr: "Pane Şnitzel (Büyük)",
    price: 600,
    category: "dishes",
  },
  // Meat Dishes
  {
    id: "22",
    nameEn: "Roasted Meat",
    nameAr: "طلب لحمة محمرة",
    nameRu: "Жареное мясо",
    nameTr: "Kavurma Et",
    price: 300,
    category: "meat",
  },
  {
    id: "23",
    nameEn: "Meat Kabab Halla",
    nameAr: "طلب لحمة كباب حلة",
    nameRu: "Мясной кабаб халла",
    nameTr: "Et Kebap Güveç",
    price: 350,
    category: "meat",
  },
  {
    id: "24",
    nameEn: "Alexandrian Liver with Bread & Tahini",
    nameAr: "طلب كبدة اسكندراني مع عيش وطحينة",
    nameRu: "Александрийская печень с хлебом и тахини",
    nameTr: "İskenderiye Ciğer Ekmek ve Tahin ile",
    price: 450,
    category: "meat",
  },
  // Gollash & Bechamel
  {
    id: "25",
    nameEn: "Gollash with Meat (1 piece)",
    nameAr: "قطعة جلاش باللحمة",
    nameRu: "Голлаш с мясом (1 шт)",
    nameTr: "Etli Gollash (1 adet)",
    price: 75,
    category: "dishes",
  },
  {
    id: "26",
    nameEn: "Gollash with Chicken (1 piece)",
    nameAr: "قطعة جلاش بالفراخ",
    nameRu: "Голлаш с курицей (1 шт)",
    nameTr: "Tavuklu Gollash (1 adet)",
    price: 65,
    category: "dishes",
  },
  {
    id: "27",
    nameEn: "Bechamel (1 piece)",
    nameAr: "بشاميل قطعة واحدة",
    nameRu: "Бешамель (1 шт)",
    nameTr: "Beşamel (1 adet)",
    price: 150,
    category: "dishes",
  },
  {
    id: "28",
    nameEn: "Bechamel (3 pieces)",
    nameAr: "بشاميل 3 قطع",
    nameRu: "Бешамель (3 шт)",
    nameTr: "Beşamel (3 adet)",
    price: 325,
    category: "dishes",
  },
  {
    id: "29",
    nameEn: "Reqaq with Meat (1 piece)",
    nameAr: "قطعة رقاق باللحمة",
    nameRu: "Ракак с мясом (1 шт)",
    nameTr: "Etli Reqaq (1 adet)",
    price: 85,
    category: "dishes",
  },
  // Sides & Salads
  {
    id: "30",
    nameEn: "Green Salad",
    nameAr: "سلطة خضراء",
    nameRu: "Зеленый салат",
    nameTr: "Yeşil Salata",
    price: 85,
    category: "sides",
  },
  {
    id: "31",
    nameEn: "Yogurt Cucumber Salad",
    nameAr: "سلطة زبادي بالخيار",
    nameRu: "Салат йогурт с огурцом",
    nameTr: "Cacık",
    price: 80,
    category: "sides",
  },
  {
    id: "32",
    nameEn: "Tahini Salad (Small)",
    nameAr: "سلطة طحينة صغيرة",
    nameRu: "Салат тахини (маленький)",
    nameTr: "Tahin Salata (Küçük)",
    price: 50,
    category: "sides",
  },
  {
    id: "33",
    nameEn: "Baba Ghanouj (Small)",
    nameAr: "بابا غنوج صغيرة",
    nameRu: "Баба гануш (маленький)",
    nameTr: "Patlıcan Ezmesi (Küçük)",
    price: 80,
    category: "sides",
  },
  {
    id: "34",
    nameEn: "Baba Ghanouj (Large)",
    nameAr: "بابا غنوج كبيرة",
    nameRu: "Баба гануш (большой)",
    nameTr: "Patlıcan Ezmesi (Büyük)",
    price: 150,
    category: "sides",
  },
  // Vegetable Dishes
  {
    id: "35",
    nameEn: "Okra Dish",
    nameAr: "طبق بامية",
    nameRu: "Блюдо из бамии",
    nameTr: "Bamya",
    price: 150,
    category: "sides",
  },
  {
    id: "36",
    nameEn: "Molokhia Dish",
    nameAr: "طبق ملوخية",
    nameRu: "Блюдо мулухия",
    nameTr: "Mulukhia",
    price: 150,
    category: "sides",
  },
  {
    id: "37",
    nameEn: "Peas with Carrots",
    nameAr: "طبق بسلة بالجزر",
    nameRu: "Горошек с морковью",
    nameTr: "Bezelyeli Havuç",
    price: 140,
    category: "sides",
  },
  // Soups
  {
    id: "38",
    nameEn: "Vegetable Soup",
    nameAr: "شوربة خضار",
    nameRu: "Овощной суп",
    nameTr: "Sebze Çorbası",
    price: 150,
    category: "soups",
  },
  {
    id: "39",
    nameEn: "Lentil Soup",
    nameAr: "شوربة عدس",
    nameRu: "Чечевичный суп",
    nameTr: "Mercimek Çorbası",
    price: 150,
    category: "soups",
  },
  {
    id: "40",
    nameEn: "Kawari Soup (Boneless Pieces)",
    nameAr: "شوربة قطع كوارع مخلية",
    nameRu: "Суп каваръ (без костей)",
    nameTr: "Paça Çorbası (Kemiksiz)",
    price: 200,
    category: "soups",
  },
  {
    id: "41",
    nameEn: "Orzo Soup",
    nameAr: "شوربة لسان عصفور",
    nameRu: "Суп орзо",
    nameTr: "Şehriye Çorbası",
    price: 90,
    category: "soups",
  },
  {
    id: "42",
    nameEn: "Plain Soup",
    nameAr: "شوربة سادة",
    nameRu: "Простой суп",
    nameTr: "Sade Çorba",
    price: 75,
    category: "soups",
  },
  // Drinks & Desserts
  {
    id: "43",
    nameEn: "Fresh Juice (Large)",
    nameAr: "عصاير طبيعية أزازة كبيرة",
    nameRu: "Свежий сок (большой)",
    nameTr: "Taze Meyve Suyu (Büyük)",
    price: 200,
    category: "drinks",
  },
  {
    id: "44",
    nameEn: "Fresh Juice (Small)",
    nameAr: "عصاير طبيعية أزازة صغيرة",
    nameRu: "Свежий сок (маленький)",
    nameTr: "Taze Meyve Suyu (Küçük)",
    price: 90,
    category: "drinks",
  },
  {
    id: "45",
    nameEn: "Basbousa with Ghee",
    nameAr: "بسبوسة بالسمنة البلدي",
    nameRu: "Басбуса с топленым маслом",
    nameTr: "Tereyağlı Revani",
    price: 150,
    category: "drinks",
  },
]

export const categories = [
  { id: "meals", en: "Main Meals", ar: "الوجبات الرئيسية", ru: "Основные блюда", tr: "Ana Yemekler" },
  { id: "dishes", en: "Dishes", ar: "الأطباق", ru: "Блюда", tr: "Tabaklar" },
  { id: "meat", en: "Meat Dishes", ar: "أطباق اللحوم", ru: "Мясные блюда", tr: "Et Yemekleri" },
  { id: "sides", en: "Sides & Salads", ar: "المقبلات والسلطات", ru: "Гарниры и салаты", tr: "Mezeler ve Salatalar" },
  { id: "soups", en: "Soups", ar: "الشوربة", ru: "Супы", tr: "Çorbalar" },
  { id: "drinks", en: "Drinks & Desserts", ar: "المشروبات والحلويات", ru: "Напитки и десерты", tr: "İçecekler ve Tatlılar" },
]
